export default function Head() {
    return (
     <>
       <title>Create Mike Page</title>
       <meta content="width=device-width, initial-scale=1" name="view" />
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
     </>


    )
}